### ISSUE TITLE
iOS not able to share local Video File with Text in Whats App

### ISSUE THREAD

**Issue by DeepashreeB** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#12]
ByteData bytes = await rootBundle.load(playListLocalPath);
                  Uint8List list = bytes.buffer.asUint8List();
                  ShareFilesAndScreenshotWidgets().shareFile(
                      "Title", "Name.mp4", list, "video/mp4",
                      text: "This is the caption!"
                      );

**Comment by JayTWWM** [comment]
What is the error that you're getting??
