### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method file on channel channel:share_files_and_screenshot_widgets)

### ISSUE THREAD

**Issue by remmss** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#13]
I am getting this error both android and ios. How can i solve this?

**Comment by MrCsabaToth** [comment]
On Android possibly you can fix it with some ProGuard rules https://csaba.page/blog/flutter-android-crash-remedies.html

**Comment by MrCsabaToth** [comment]
To be more specific if someone finds this, the ProGuard rules related to this plugin:
```
-keep class com.twwm.share_files_and_screenshot_widgets.** { *; }
-keepclassmembernames class com.twwm.share_files_and_screenshot_widgets.** { *; }
```
However please study the other rules mentioned in my blog post as well.
