### ISSUE TITLE
Introduce null safety

### ISSUE THREAD

**Issue by MrCsabaToth** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#14]
Right now the package doesn't support null safety and that poses a problem with sound null safe projects.

> The library 'package:share_files_and_screenshot_widgets/share_files_and_screenshot_widgets.dart' is legacy, and should not be imported into a null safe library.

**Comment by seifkh97** [comment]
pls introduce null safety

**Comment by MrCsabaToth** [comment]
> pls introduce null safety

If you don't care about the screenshot feature or image sharing then I have a null-safe fork: https://github.com/CsabaConsulting/Share-Files-And-Screenshot-Widgets-Flutter/
I'm using it to share non image files. You can refer to it in your `pubspec.yaml` like:
```
  share_files_and_screenshot_widgets:
    git:
      url: https://github.com/CsabaConsulting/Share-Files-And-Screenshot-Widgets-Flutter.git
```
Upgrading one of my Flutter project to null safety was a shit show: https://csaba.page/blog/flutter-dart-sound-null-safety.html

**Comment by JayTWWM** [comment]
Done
