### ISSUE TITLE
Upgrade to Android V2 embedding to not rely on deprecated API

### ISSUE THREAD

**Issue by MrCsabaToth** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#16]
V2 is out there for a good while now and the time is ticking: Android Studio presents a warning

> The plugins `bluetooth_enable, share_files_and_screenshot_widgets` use a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by JayTWWM** [comment]
Done
