### ISSUE TITLE
Hide certain elements within the widget from appearing the screenshot

### ISSUE THREAD

**Issue by smarthorizons** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#2]
Thanks, for the code, it works fine. 
Questions, if I use a card instead of container and put an icon in the card to be pressed to screenshot and share the card.
Is there a way to hide this icon from appearing in the card screenshot?

_Originally posted by @moosalim in https://github.com/JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter/issues/1#issuecomment-674434890_

**Comment by moosalim** [comment]
Thanks for suggestion, good idea. but I could not do it. Can you please help me with sample code. 
I will highly appreciate your support.

**Comment by JayTWWM** [comment]
Just use a stack and put two different widgets in it..........
One will be the screenshot widget and another will be just an overlay

**Comment by moosalim** [comment]
Hello @JayTWWM 

it is me after long time.
I have tried your suggestion to use dummy widget hidden within a Stack, but no use. Your plugin seems not working if the widget is not visible.
