### ISSUE TITLE
offset on iOS

### ISSUE THREAD

**Issue by nitneuq33000** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#3]
Hello, I have same trouble with other "screenshot and share" package. If I open share pop up, next I choose facebook, next I make fall the keyboard and after publish or cancel and close pop up, I have 1/4 of my screen with offset and impossible to remove without close app 
![RPReplay_Final1598707827](https://user-images.githubusercontent.com/38652337/91638192-d0fdf480-ea0d-11ea-8836-4546942b16d6.gif)

**Comment by JayTWWM** [comment]
I did not understand the problem . Can you please explain it ?

**Comment by nitneuq33000** [comment]
Ok first,bottom offset only appear on iphone

Here is step to reproduce

- take a screenshot
- open the share windows
- select facebook ( keyboard will automatically show)
- important bug appear only if the keybord is hide, to do this I scroll
down to push down the keyboard
- after there is no keyboard publish or cancel to quit the page
- after all this things a bottom offset appear who take 1/4 of the screen.
And it’s impossible to remove

**Comment by JayTWWM** [comment]
Can 6ou share your implemented code?

**Comment by nitneuq33000** [comment]
Issue is repeatable with the package example 

![RPReplay-Final1599023204](https://user-images.githubusercontent.com/38652337/91934287-48bc6f80-eceb-11ea-9f1f-1a3a46aa0bba.gif)

**Comment by JayTWWM** [comment]
Okay got it.
Thanks for adding the issue......will fix it asap

**Comment by JayTWWM** [comment]
I have tried and tested everything, it is not related to the pub.........
It is a flutter layer bug or something like that........
The offset doesn't have anything to do with the plugin functionality

**Comment by nitneuq33000** [comment]
Thank you for this information.
