### ISSUE TITLE
Security IOS 'Save Image'

### ISSUE THREAD

**Issue by mstolk** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#4]
Hi, 

I'm getting a '__CRASHING_DUE_TO_PRIVACY_VIOLATION__' error while choosing 'Save Image' in the share popup on iOS. What kind of security settings do i need for this option? I added some to the plist but i think i'm missing some.

Marco

**Comment by JayTWWM** [comment]
Thanks for this issue I'll get back to you in some time

**Comment by JayTWWM** [comment]
If you're seeing these crashes on iPhone X and you use Touch ID/Face ID, the reason might be a lack of NSFaceIDUsageDescription key in your Info.plist. The key was added in iOS 11 and looks like it might have become mandatory after iOS 11.3, given that I see a spike of crashes on iPhone X after iOS 11.3 was released.

**Comment by mstolk** [comment]
Hi, just fixed it. The solution was adding the plist options:
NSFaceIDUsageDescription
NSPhotoLibraryAddUsageDescription
NSPhotoLibraryUsageDescription

Maybe you can put it in the documentation of the code somewhere, to help out other users.

Thanks for the help and input and keep up the good work

**Comment by rootasjey** [comment]
Only `NSPhotoLibraryAddUsageDescription` is needed though if you only want to write to the photo library. 
More info in this [stackoverflow question](https://stackoverflow.com/questions/46344159/whats-difference-between-nsphotolibraryaddusagedescription-and-nsphotolibraryus).
