### ISSUE TITLE
Some user can't take screenshot

### ISSUE THREAD

**Issue by nitneuq33** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#7]
Hello, I add this plugin in my app. It work's great for me on all my physical device and after release on playstore, but I have some feedback of users who can't take screenshot.. All users confirmed the validation of stockage authorization, but even this, their can't use this function. 

thank you

**Comment by JayTWWM** [comment]
Can you see if their android and iOS versions are compatible.
