### ISSUE TITLE
Error permission

### ISSUE THREAD

**Issue by VictorPadovan1997** [JayTWWM/Share-Files-And-Screenshot-Widgets-Flutter#9]
This my problem....

E/DatabaseUtils(21057): java.lang.SecurityException: Permission Denial: reading com.twwm.share_files_and_screenshot_widgets.ShareFilesAndScreenshotWidgetsFileProvider uri content://coesma.nit.eletronica.fileprovider.share_files_and_screenshot_widgets/cache/segundaviaAitNIT.png from pid=21789, uid=1000 requires the provider be exported, or grantUriPermission()

**Comment by JayTWWM** [comment]
Can you share you code and flutter doctor cmd output.
